### ISSUE TITLE
Fixing the Cursive issue with finding the project deps.edn

### ISSUE THREAD

**Issue by atroche** [RickMoynihan/lein-tools-deps#22]
From @mfikes's [Cursive workarounds gist](https://gist.github.com/mfikes/f803fef3013927c376063a3d72b69d60):

> When processing project.clj, Cursive will be running with a working directory such as /Applications/IntelliJ IDEA.app/Contents/bin (i.e. not your project directory). This will cause lein-tools-deps to fail to find project-level deps.edn file

Instead of [using](https://github.com/RickMoynihan/lein-tools-deps/blob/master/src/lein_tools_deps/plugin.clj#L19) the `clojure.tools.deps.alpha.reader/clojure-env` fn (which uses `clojure -Sdescribe` under the hood) to get the project deps.edn, is there a way we could use leiningen's knowledge of the location of the project.clj file?

**Comment by RickMoynihan** [comment]
> ... is there a way we could use leiningen's knowledge of the location of the project.clj file?

Sadly not.  We're doing this already in PR #21 for other reasons; but the reason we need to shell out is to capture the location of the `:system` level `deps.edn` (we also get `:home` this way though we could easily infer that ourselves if we needed to).

The `:system` level `deps.edn` can be installed in different locations depending on the version of tools.deps, your O/S and the package manager.  e.g. on macOS my system deps.edn is in:

`/usr/local/Cellar/clojure/1.9.0.375/deps.edn`

Personally I think on mac with homebrew this should probably be symlinked from `/usr/local/etc/deps.edn`, in the same way that the latest `clj` / `clojure` scripts are by default symlinked into `/usr/local/bin` but I don't really know enough about brew as to whether this is the done thing or not.

Assuming `tools.deps` choose to do this, we'd still want to allow some overrides for these aliases for situations where people install these into non-standard locations.

**Comment by atroche** [comment]
Oh, couldn't you shell out for `:system` and `:home` but get the location of the `:project` deps file through lein? I guess that'd be a bit of a hack and probably only useful for Cursive users.

If https://github.com/RickMoynihan/lein-tools-deps/pull/21 lands then I'll be able to do `[:system :home "deps.edn"]` and that will achieve the same thing, so I'm happy :)

**Comment by atroche** [comment]
Oh, whoops, after reading more carefully I can see that #21 also handles the `:project` case for Cursive. Awesome!

**Comment by atroche** [comment]
How about using [with-sh-env](https://github.com/clojure/clojure/blob/fe0cfc71e6ec7b546066188c555b01dae0e368e8/src/clj/clojure/java/shell.clj#L28) to add `/usr/local/bin/` to the path when we make [the call to `clojure-env`](https://github.com/RickMoynihan/lein-tools-deps/blob/16fdf82158e51a3be70a77a6f97afd98740515b0/src/lein_tools_deps/plugin.clj#L19)?

**Comment by mfikes** [comment]
I can try that @atroche . I suspect it won't work because the environment is passed to the _launched_ process (it is not used in the _current_ process to launch the launched process).

**Comment by atroche** [comment]
I've been messing around with this, and I'm wondering if there's a better workflow than what I'm doing at the moment:

1. make a change to the source of the plugin.
2. run `lein install`
3. Run “Refresh Leiningen Projects” in Cursive (on a project that uses `lein-deps-tools`)
4. Occasionally restart Cursive when I start getting cryptic errors about ZLib or “code lengths”

And the thing that's probably slowing me down the most is not being able to read the `println`s I do in the plugin, from within Cursive. The only error messages I can reliably get look like this:

```
5:50 PM	Error reading /Users/alistair/clj/blah/project.clj
				Cannot run program "clojure": error=2, No such file or directory
				error=2, No such file or directory

5:51 PM	Error reading /Users/alistair/clj/blah/project.clj
```

Are you faring better, @mfikes ?

**Comment by mfikes** [comment]
@atroche If there is some details I want to know, I've resorted to having the plugin throw a `RuntimeException` with the text containing what I'd like to see.

**Comment by mfikes** [comment]
I don't know. I've been doing `lein install` as well.

**Comment by RickMoynihan** [comment]
@atroche @mfikes You shouldn't need to do `lein install` each time.  Simply add a `.lein-classpath` file in to your project and point it to the `src` directory for `lein-tools-deps.  See the example project for a concrete example of this working:

https://github.com/RickMoynihan/lein-tools-deps/blob/247336c1d2834a3d1d7bd66aecc7172ba511e562/example/.lein-classpath#L1

Also the [leiningen writing a plugin](https://github.com/technomancy/leiningen/blob/stable/doc/PLUGINS.md#writing-a-plugin) docs.

I should also say my preferred workflow has been to just run `lein repl` within the `lein-tools-deps` project root, and just link directly to `deps.edn` files, that way you can just evaluate forms like:

`(resolve-deps (canonicalise-dep-locs [:system :home "example/deps.edn" "foo"]))`

Hope that helps.

**Comment by atroche** [comment]
Awesome, the `.lein-classpath` solution works great.

**Comment by mfikes** [comment]
The patch in https://github.com/RickMoynihan/lein-tools-deps/pull/31 would have `lein-tools-deps` fall back to trying `/usr/local/bin/clojure` if it exists and `clojure` fails.
