### ISSUE TITLE
How should we handle deps.edn :local/root 

### ISSUE THREAD

**Issue by RickMoynihan** [RickMoynihan/lein-tools-deps#5]
Thinking we should just throw these onto the leiningen `:source-path`.

**Comment by phreed** [comment]
Would throwing `:local/root` into the `:source-path` fix my problem?

```
{ :paths ["src"]
  :deps {...
             foo {:local/root "/home/foo.SNAPSHOT-maven-jar-with-dependencies.jar"}
             ...}
  :mvn/repos ...
}
```

I am currently getting an error with: uberjar, compile, etc..

> Uberjar aborting because jar failed: Provided artifact is missing a version: [foo/foo nil]

**Comment by RickMoynihan** [comment]
Hi @phreed, 

Yes `lein-tools-deps` needs to handle `:local/root`'s essentially by conjing them into the leiningen `:source-path`.  We may need to check how `tools.deps` resolves conflicts within the source path, i.e. whether there is a deterministic way to order them with relation to each other.  IIRC @puredanger has mentioned this somewhere; so we should check; but I suspect they rely on there not being any conflicts on the classpath here.

Regarding the specifc example you've pasted because you've elided a lot of the config and possibly some of the error message it's hard for me to see what exactly you're trying to do.

For example I'm not sure why you'd want to use `:local/root` with what looks to be a maven dependency (`:mvn/version` will resolve these) or uberjar (which would work but would likely be a bad idea).

**Comment by RickMoynihan** [comment]
@phreed it's hard to offer a recommendation without knowing what you're trying to achieve (and why), beyond that I'd suggest you use the standard tools for the job, i.e. `:mvn/version` library jar artifacts, or a`:local/root` to another tools deps project directory (or a library jar), or a `:git/url` to a library jar.

(Bearing in mind of course this lein plugin only supports mvn/leiningen deps just now.)

Whilst tools.deps won't care that you're linking to an uberjar, I'd imagine you should be very careful if you do that.  I'd basically only do it if you have very good reasons, and I'd be clear that you understand the implications and risks of doing it; and even then I'd try to avoid it like the plague.

Basically the primary usecase for uberjars is to release an application as a single executable jar file, not to release libraries.  

Uberjar's shouldn't typically be used for libraries as the libraries uberjar will (unless you've taken great care curating its contents) contain all dependencies of that library, preventing mvn/lein/tools.deps from resolving the dependencies on it and its contents, and making your library a lot less reusable.  e.g. imagine your uberjar'd library depends on clojure 1.8, but as a developer I want to consume your library into my app which uses clojure 1.9.  Ordinarily (i.e. with a standard mvn/lein dep), this should work without too many problems (as the mvn/tools.deps/lein will pick a single clojure version that wins for you) but if that library is an uberjar it will likely also contain clojure itself, meaning clojure 1.8 and 1.9 would be combined together on the classpath resulting in a very confusing mess where some code would be from 1.9 and some from 1.8, parts of the app might see 1.9 and other parts 1.8 (depending on what they're doing) and clojure itself may find it interfering with itself, resulting in very, very confusing errors.

I hope that makes sense.

**Comment by RickMoynihan** [comment]
Initial support for `:git/url` and `:local/root` can be found on the `git-and-local-root-deps` branch:

https://github.com/RickMoynihan/lein-tools-deps/compare/git-and-local-root-deps

Just a first stab at it, it seems to work - but it's late and I'd like to test it a little more before releasing.
