### ISSUE TITLE
How can we resolve system deps.edn in an O/S agnostic way?

### ISSUE THREAD

**Issue by RickMoynihan** [RickMoynihan/lein-tools-deps#6]
This is currently hardcoded for OSX/homebrew:

https://github.com/RickMoynihan/lein-tools-deps/blob/9ec8ca17ef2fa85010af67bcf0bf58124e696c88/src/lein_tools_deps/plugin.clj#L13

**Comment by marco-m** [comment]
Partial answer, still focusing on MacOS: the current approach assumes that
1. homebrew install is using default prefix /usr/local
2. hardcoded specific clojure version (already now that version is outdated)

I would suggest to use the `brew` utility to lookup at runtime. For example

```
$ brew list clojure | grep /deps\.edn
/usr/local/Cellar/clojure/1.9.0.302/deps.edn
```

would be prefix-independent and adapt to the currently installed Clojure version.

Maybe another possibility would be to introspect Clojure itself from within the Lein JVM instance ?

**Comment by RickMoynihan** [comment]
Thanks for this.

I was hoping we could pursuade @puredanger to provide a platform independent way to get these locations, though it might not be possible.

If not we can probably inspect the classpath to find the version of the `tools.deps.jar` being used, parse its version number and then make a reasonable assumption about the default path root being used on the OS/arch we're running on.

On the occaisions the assumption we make is false users could override the default chain of `deps.edn` files via a profile or their `project.clj`.  We could perhaps even add a new key called something like `:deps-edn-install-root`.

I'm not completely against shelling out to brew or an equivalent, but I think what I've described above might be a more general approach.

**Comment by slipset** [comment]
From the Clojurians slack
@seancorfield Where `lein-tools-deps` assumes `(def system-deps (io/file "/usr/local/Cellar/clojure/1.9.0.297/deps.edn"))`, `boot-tools-deps` pulls it from `brew-install` *master* when I build it and bundles it with `boot-tools-deps` -- figuring out the "right" way to include that system deps file is hard.

@puredanger: there is actually a new api we’re working on to shell out to `clojure` to get the list of deps files in play
