### ISSUE TITLE
Plugin doesn't respect PATH

### ISSUE THREAD

**Issue by kmrozek-shareablee** [RickMoynihan/lein-tools-deps#62]
You can't specify `clojure` in a clojure-executables option. That's because it tries to check the existence of `clojure` and it is not there, so it throws an error. Why not just execute `clojure` with `clojure.java.shell/sh` and if there is an error (check the error code), print full response of an error or throw the full response as an exception.

**Comment by agzam** [comment]
is there an update on this, I'm having trouble running `docker build` it complains: `clojure.lang.ExceptionInfo: Could not find clojure executable`
