### ISSUE TITLE
Docs question: to what do the keywords :install :user and :project refer?

### ISSUE THREAD

**Issue by ezmiller** [RickMoynihan/lein-tools-deps#68]
The docs suggest a set of keywords to be used in the default configuration:

> `:lein-tools-deps/config {:config-files [:install :user :project]}`

I don't understand -- and I'm by no means a leingen expert -- what these keywords are indicating. I thought they might be a way to refer to the name of `deps.edn` files that are for some reason named alternately since the docs later say under the `:config-files` option that values for this option should be:

> A vector referencing an ordered collection of deps.edn files that will be used for dependency resolution. Each file should be either a file path string or a special keyword (:install :user or :project).

But then I looked at the example and saw that this suggested config is used and yet the only dependency file is called `deps.edn`. 

I'm sure that there's some fundamental lack of knowledge causing to be confused here, but I wonder if others might also be confused. Is there any way to clarify this?

**Comment by lkitching** [comment]
@ezmiller @GS-JS @timgilbert - We've updated the readme to describe the meaning of those keys, please let me know if they're still unclear.
