### ISSUE TITLE
Cannot find tools.deps.alpha

### ISSUE THREAD

**Issue by grav** [RickMoynihan/lein-tools-deps#7]
I get the following exception when running `lein deps` on the example project:

```
$ lein deps
Retrieving lein-tools-deps/lein-tools-deps/0.1.0-SNAPSHOT/lein-tools-deps-0.1.0-20171214.014635-1.pom from clojars
Retrieving lein-tools-deps/lein-tools-deps/0.1.0-SNAPSHOT/lein-tools-deps-0.1.0-20171214.014635-1.jar from clojars
Could not find artifact org.clojure:tools.deps.alpha:jar:0.2.197-SNAPSHOT in clojars (https://repo.clojars.org/)
```

I tried updating the `tools.deps.alpha` to the latest version (`0.3.260`), which doesn't work, probably because the interface has changed.

Updating to a previous version, `tools.deps.alpha-0.2.196`, seems to fix it.

**Comment by RickMoynihan** [comment]
Hi @grav... thanks for reporting.  I've known things have been broken since more or less the day after I first got it working (for some level of working).  I think at the time there was no deployed release for the artifact published for 0.2.196, so I'd locally built a SNAPSHOT; but since then things seem to have changed a bit.

I tried bumping some versions and accounting for some of the code changes the other day and have pushed those to master, but things still seem to be broken for the example; and I've not had time to investigate the issue further.

Do you have a patch in which the example appears to work?

**Comment by RickMoynihan** [comment]
Hi @grav,

I've recently bumped some versions and fixed some issues, and can't recreate your issue now:

e.g.

```
$ cd ~/repos/lein-tools-deps/example
$ rm -rf ~/.m2/repository/criterium
$ lein deps
Downloading: criterium/criterium/0.4.4/criterium-0.4.4.pom from https://clojars.org/repo/
Downloading: criterium/criterium/0.4.4/criterium-0.4.4.jar from https://clojars.org/repo/
$ 
```

Can you try updating to the latest commit on master?  And rerunning to see if you can recreate the issue?  

It would also help to know what version of the `clj` command line tools you have installed.

**Comment by mfikes** [comment]
Could a new version of `lein-tools-deps` be deployed?

It would be nice to experiment with this plugin, but this issue seems to limit such experimentation to local boxes (in other words, this prevents experimentation in projects that use CI systems).

**Comment by RickMoynihan** [comment]
@mfikes sure good idea.  I was using a local install for dev, so forgot that I hadn't deployed a new one.

I've deployed under a new `0.2.0-SNAPSHOT` minor version; which should feature the git deps stuff (though bear in mind that stuff was only tested locally, late at night, etc etc... - see #5).

Let me know how you get on.  I'm pretty sure I can probably close this issue now, but will wait for some 3rd party confirmation.

**Comment by mfikes** [comment]
Thanks @RickMoynihan !

Things work for me with `0.2.0-SNAPSHOT`. For example, if I have `deps.edn` with

```
{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.12"}}}
```

then `lein repl` starts up properly.

**Comment by RickMoynihan** [comment]
@mfikes done.
