### ISSUE TITLE
Unnecessary dependencies when deploying to clojars

### ISSUE THREAD

**Issue by denisidoro** [RickMoynihan/lein-tools-deps#73]
When using lein-tools-deps and deploying a library to clojars, unnecessary dependencies are required.

- [Deps with lein-tools-deps](https://clojars.org/denisidoro/quark/versions/0.4.0)
- [Deps without lein-tools-deps](https://clojars.org/denisidoro/quark/versions/0.4.1)
- [Change in code](https://github.com/denisidoro/quark/pull/5/files)

**Comment by RickMoynihan** [comment]
Hi,

I suspect part of this is just an artifact of how `lein-tools-deps` works, which is that it uses `tools.deps` to resolve all dependencies, and then it flattens the dependency tree and inserts it into your `:dependencies` vector.  The reason we flatten the tree with all transitive dependencies is that it should guarantee that `tools.deps` and `leiningen` resolve the same dependencies.  (Alex Miller has reported that `tools.deps` adopts a different resolution to maven/leiningen).

So I suspect what you're seeing is just all the transitive dependencies being lifted to the top level.

However, I took a quick look at it appears there are a few other dependencies being included too.  Can you guarantee that the deploy of those jars was for between those commits, and that no other profiles were at play?  If so it would be good to figure out where those dependencies are coming from.

**Comment by RickMoynihan** [comment]
Oh one other thing you've included your `deps.edn` twice; I don't know if that is causing a problem, but you should be able to remove `"./deps.edn"` from your config-files vector as `:project` refers to that file too.

**Comment by RickMoynihan** [comment]
Closing this issue for the more specific https://github.com/RickMoynihan/lein-tools-deps/issues/73
