### ISSUE TITLE
Dependencies with a classifier resolved incorrectly

### ISSUE THREAD

**Issue by lkitching** [RickMoynihan/lein-tools-deps#80]
`tools.deps` used to use the `:classifier` key within the dependency map to specify the classifier e.g.

```clojure
groupId/artifactId {:mvn/version "1.0.0" :classifier "prod"}
```

this has now changed to specifying the classifier in the artifact name i.e.

```clojure
groupId/artifactId$classifier {:mvn/version "1.0.0"}
```

`lein-project/leinize` should be updated to reflect this change.

**Comment by RickMoynihan** [comment]
Thanks for reporting @lkitching.
