### ISSUE TITLE
dep on org.clojure/tools.deps.alpha causes com.google.inject:guice$no_aop:jar:4.0  not found

### ISSUE THREAD

**Issue by oceangroove** [RickMoynihan/lein-tools-deps#87]
I really hope I haven't made a stupid error, if so sorry.
It seems that if I have a deps.edn with 
```
org.clojure/tools.deps.alpha {:mvn/version "0.6.496"}}
```
 or I have a deps.edn that depends on a project with this dependency either via a mvn/clojars or via a git dep with :deps/manifest :deps I get an error like

```
Could not find artifact com.google.inject:guice$no_aop:jar:4.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.google.inject:guice$no_aop:jar:4.0 in clojars (https://repo.clojars.org/) 
```
I have tried downloading and installing these jars (from google)  into my repo but the naming seems to be broken in some way.  

To recreate 

Simple project.clj 
```
(defproject test-lein-tools-deps "0.0.1"
  :plugins [[lein-tools-deps "0.4.3"]]
  :middleware [lein-tools-deps.plugin/resolve-dependencies-with-deps-edn]
  :lein-tools-deps/config {:config-files ["deps.edn"]})
```
deps.edn

```
{:deps {org.clojure/clojure         {:mvn/version "1.10.0"}
             org.clojure/tools.deps.alpha {:mvn/version "0.6.496"}}
 :mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
                      "clojars" {:url "https://repo.clojars.org/"}}
 :paths ["src/clj"]}
```

move  ~/.m2/repository somewhere safe
move  ~/.gitlibs/libs somewhere safe

then 
lien deps

Java 8 OR java 11 openJDK

lein Leiningen 2.9.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM

Leiningen 2.9.1 on Java 11.0.2 OpenJDK 64-Bit Server VM

macos 10.12.5

**Comment by lkitching** [comment]
Hi, this looks like another instance of #80. Version `0.4.5` has just been released which hopefully should fix this. Could you try that version?

**Comment by oceangroove** [comment]
Hi, thanks - on my simple example above the upgrade has fixed the problem.  Will try it out on more complex deps in the next couple of hours.  Thanks again.

**Comment by oceangroove** [comment]
Hi, yes this seems to have fixed it for more complex hierarchical projects.
Thanks again.

**Comment by RickMoynihan** [comment]
Great!
